### ISSUE TITLE
Game Ideas

### ISSUE THREAD

**Issue by aec1140** [aec1140/sugarizer#1]
**Post Here Example of what gameplay you feel we should have? I feel we should stick with math**

**Comment by CoffeeFrame** [comment]
If you've played typing of the dead, maybe something similar to that with simple math problems and less vulgarity? That would reinforce quick solving of problems.

**Comment by Awmusic12635** [comment]
Could do some type of match competition. Perhaps who can solve the most in a certain period of time?

Or maybe something with geometry and shape matching.

**Comment by aec1140** [comment]
How about something like candy crush where items that match one way get deleted. Instead of color, it will be shapes and inside the shapes will be a fraction. You can either match shapes that have common characteristics or fractions that equal the same. If you get both we could do something that maybe creates a bomb or something etc.

**Comment by Awmusic12635** [comment]
Interesting idea. I like it. 

Another question we should think about. Should we focus on doing a single topic for the game or tackle more than one (fractions and shapes in the case of your example) within the same game?

If this is for a lesson plan then it might be better to have a game for a specific concept.

**Comment by aec1140** [comment]
hmm we could stick with fractions. I'm wondering if we should only work with matching fractions, or, if we should allow two fractions to be added to each other as well

**Comment by aec1140** [comment]
so if 1/2 and 1/2 were selected the blocks would disappear, but if 1/4 and 1/2 were selected one block would appear that is 3/4
